# Generated by Django 4.2.20 on 2025-04-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MucSuperAdmin',
            fields=[
                ('suparadmin_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created', models.BigIntegerField(default=0)),
                ('modified', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'superadmin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MucUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'muc_user',
            },
        ),
    ]
