# Generated by Django 4.2.20 on 2025-04-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mucsuperadmin',
            old_name='row_id',
            new_name='superadmin_id',
        ),
        migrations.AlterField(
            model_name='mucsuperadmin',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mucsuperadmin',
            name='created',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mucsuperadmin',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mucsuperadmin',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mucsuperadmin',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mucsuperadmin',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mucsuperadmin',
            name='modified',
            field=models.BigIntegerField(default=0),
        ),
    ]
