# Generated by Django 4.2.20 on 2025-04-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_row_id_mucsuperadmin_suparadmin_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mucsuperadmin',
            options={'managed': False},
        ),
    ]
