# Generated by Django 4.2.20 on 2025-04-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_mucsuperadmin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mucsuperadmin',
            options={},
        ),
    ]
