# Generated by Django 4.2.20 on 2025-04-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_mucsuperadmin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mucsuperadmin',
            options={'managed': False},
        ),
    ]
