# Generated by Django 4.2.20 on 2025-08-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MucUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('created_on', models.BigIntegerField(default=0)),
                ('modified_on', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'muc_user',
                'managed': False,
            },
        ),
    ]
